apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: k8s-kops
        image: dirivio/petclinic
        ports:
        - containerPort: 8080
